stages:
  - docker
  - build
  - tests

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

Docker:
  stage: docker
  image: docker:dind
  script:
    # start docker daemon and give it time before making request
    - dockerd >/dev/null 2>&1 &
    - sleep 5 
    # unset docker host so requests go to local service
    - unset DOCKER_HOST
    # enable docker buildkit so caching options work
    - export DOCKER_BUILDKIT=1
    # build and push image
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - >
      docker build
      --cache-from $DOCKER_IMAGE
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag $DOCKER_IMAGE
      .
    - docker push $DOCKER_IMAGE

Build:
  stage: build
  image: $DOCKER_IMAGE
  cache:
    key: build_$CI_COMMIT_REF_SLUG
    paths:
      - target/
  script:
    - make build

BuildTests:
  stage: build
  image: $DOCKER_IMAGE
  cache:
    key: build_$CI_COMMIT_REF_SLUG
    paths:
      - target/
  script:
    - make build-tests
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

RunTests:
  stage: tests
  image: $DOCKER_IMAGE
  script:
    - make clean-test
    - make test
