stages:
  - docker
  - build
  - tests

services:
  - docker:dind

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

Docker:
  stage: docker
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

Build:
  stage: build
  image: $DOCKER_IMAGE
  cache:
    key: build_$CI_COMMIT_REF_SLUG
    paths:
      - target/
  script:
    - make build

BuildTests:
  stage: build
  image: $DOCKER_IMAGE
  cache:
    key: build_$CI_COMMIT_REF_SLUG
    paths:
      - target/
  script:
    - make build-tests
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

RunTests:
  stage: tests
  image: $DOCKER_IMAGE
  script:
    - make clean-test
    - make test
