# Rustfmt configuration
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
edition = "2018"

tab_spaces = 4
wrap_comments = false

group_imports = "StdExternalCrate"
reorder_impl_items = true
